/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package se3313project;

import java.awt.Color;
import java.awt.PopupMenu;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import static se3313project.CoffeeMakerDatabase.getConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp; 
import java.sql.*; 
import javax.swing.JLabel;

/**
 *
 * @author psk
 */
public class ViewInterface extends javax.swing.JFrame implements CoffeeMakerObserver{
 private final CoffeeMakerModel coffeeMakerModel; 
    /**
     * Creates new form ViewInterface
     */
    public ViewInterface(CoffeeMakerModel coffeeMakerModel1) {
        
        this.coffeeMakerModel = coffeeMakerModel1; // Assign the provided model

        coffeeMakerModel.addObserver(this);
        initComponents();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        filledButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        totalCupsButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        CupsTextField = new javax.swing.JTextField();
        IDLEpanel = new javax.swing.JPanel();
        jLabelIDLE = new javax.swing.JLabel();
        brewingPanel = new javax.swing.JPanel();
        jlabelBREWING = new javax.swing.JLabel();
        donePanel = new javax.swing.JPanel();
        jLabelDONE = new javax.swing.JLabel();
        TotalCupsPanel = new javax.swing.JPanel();
        totalCupsLabel = new javax.swing.JLabel();
        messagesArea = new javax.swing.JPanel();
        errorMessageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        filledButton.setBackground(new java.awt.Color(204, 255, 255));
        filledButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        filledButton.setText("FILLED");
        filledButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filledButtonActionPerformed(evt);
            }
        });

        startButton.setBackground(new java.awt.Color(204, 204, 255));
        startButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        totalCupsButton.setBackground(new java.awt.Color(204, 255, 255));
        totalCupsButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        totalCupsButton.setText("Total Cups");
        totalCupsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCupsButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(204, 204, 255));
        resetButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        CupsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CupsTextFieldActionPerformed(evt);
            }
        });

        jLabelIDLE.setFont(new java.awt.Font("Imprint MT Shadow", 2, 12)); // NOI18N
        jLabelIDLE.setText("IDLE");

        javax.swing.GroupLayout IDLEpanelLayout = new javax.swing.GroupLayout(IDLEpanel);
        IDLEpanel.setLayout(IDLEpanelLayout);
        IDLEpanelLayout.setHorizontalGroup(
            IDLEpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDLEpanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelIDLE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IDLEpanelLayout.setVerticalGroup(
            IDLEpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDLEpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIDLE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jlabelBREWING.setFont(new java.awt.Font("Imprint MT Shadow", 2, 12)); // NOI18N
        jlabelBREWING.setText("BREWING");

        javax.swing.GroupLayout brewingPanelLayout = new javax.swing.GroupLayout(brewingPanel);
        brewingPanel.setLayout(brewingPanelLayout);
        brewingPanelLayout.setHorizontalGroup(
            brewingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brewingPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlabelBREWING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        brewingPanelLayout.setVerticalGroup(
            brewingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brewingPanelLayout.createSequentialGroup()
                .addComponent(jlabelBREWING)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jLabelDONE.setFont(new java.awt.Font("Imprint MT Shadow", 2, 12)); // NOI18N
        jLabelDONE.setText("DONE");

        javax.swing.GroupLayout donePanelLayout = new javax.swing.GroupLayout(donePanel);
        donePanel.setLayout(donePanelLayout);
        donePanelLayout.setHorizontalGroup(
            donePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelDONE, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        donePanelLayout.setVerticalGroup(
            donePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDONE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        totalCupsLabel.setText(".......");

        javax.swing.GroupLayout TotalCupsPanelLayout = new javax.swing.GroupLayout(TotalCupsPanel);
        TotalCupsPanel.setLayout(TotalCupsPanelLayout);
        TotalCupsPanelLayout.setHorizontalGroup(
            TotalCupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalCupsPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(totalCupsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TotalCupsPanelLayout.setVerticalGroup(
            TotalCupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalCupsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalCupsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        errorMessageLabel.setText(".");

        javax.swing.GroupLayout messagesAreaLayout = new javax.swing.GroupLayout(messagesArea);
        messagesArea.setLayout(messagesAreaLayout);
        messagesAreaLayout.setHorizontalGroup(
            messagesAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagesAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        messagesAreaLayout.setVerticalGroup(
            messagesAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagesAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel1.setText(" Welcome to Your Coffee Maker");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filledButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CupsTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalCupsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(donePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brewingPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotalCupsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDLEpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messagesArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CupsTextField)
                    .addComponent(filledButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDLEpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brewingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalCupsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(TotalCupsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messagesArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalCupsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCupsButtonActionPerformed
       
      try{
          int totalCups=getTotalCupsFromDatabase();
          updateTotalCupsPanel(totalCups);
      }catch(SQLException ex){
          ex.printStackTrace();
      }
    }//GEN-LAST:event_totalCupsButtonActionPerformed

    private void CupsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CupsTextFieldActionPerformed
        
    }//GEN-LAST:event_CupsTextFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        coffeeMakerModel.start();
    }//GEN-LAST:event_startButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
         coffeeMakerModel.reset();
         CupsTextField.setText(""); 
         IDLEpanel.setBackground(null);
         brewingPanel.setBackground(null);
         donePanel.setBackground(null);
         coffeeMakerModel.setCurrentState(new EmptyState(coffeeMakerModel));
         
    }//GEN-LAST:event_resetButtonActionPerformed

    private void filledButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filledButtonActionPerformed
        CoffeeMakerState currentState = coffeeMakerModel.getCurrentState();
        try {
        int cups = Integer.parseInt(CupsTextField.getText());
        coffeeMakerModel.fillCups(cups);
        if(currentState instanceof EmptyState){
            coffeeMakerModel.fillCups(cups);            
              
        }else{
                  }
    } catch (NumberFormatException ex) {
        
    }
    }//GEN-LAST:event_filledButtonActionPerformed

    private int getTotalCupsFromDatabase() throws SQLException {
    try (Connection connection = getConnection()) {
        String query = "SELECT SUM(cups) FROM coffee_data";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query);
             ResultSet resultSet = preparedStatement.executeQuery()) {

            if (resultSet.next()) {
                return resultSet.getInt(1);
            }
        }
    }
    return 0; 
}

private void updateTotalCupsPanel(int totalCups) {
    
    totalCupsLabel.setText(String.valueOf(totalCups));
}
    
    
    
    
    
    public JTextField getTotalCupsTextField() {
        return CupsTextField;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                CoffeeMakerModel coffeeMakerModel = new CoffeeMakerModel();
                new ViewInterface(coffeeMakerModel).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CupsTextField;
    private javax.swing.JPanel IDLEpanel;
    private javax.swing.JPanel TotalCupsPanel;
    private javax.swing.JPanel brewingPanel;
    private javax.swing.JPanel donePanel;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JButton filledButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDONE;
    private javax.swing.JLabel jLabelIDLE;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabelBREWING;
    private javax.swing.JPanel messagesArea;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton totalCupsButton;
    private javax.swing.JLabel totalCupsLabel;
    // End of variables declaration//GEN-END:variables

    
 
     
   
    

    public void setLabelText(String text){
        errorMessageLabel.setText(text); 
    }

    
    @Override
    public void update() {
        
        updateMessagesArea();
        
    }


    private void updateMessagesArea() {
         
         
        String message = "Current State: " + coffeeMakerModel.getCurrentState().getClass().getSimpleName();
        messagesArea.toString();
    }
     
   
   

    

    
     public JButton getStartButton() {
        return startButton;
    }

    public JButton getFilledButton() {
        return filledButton;
    }

    public JButton getResetButton() {
        return resetButton;
    }

    public JPanel getIDLEpanel() {
        return IDLEpanel;
    }

    public JPanel getBrewingPanel() {
        return brewingPanel;
    }

    public JPanel getDonePanel() {
        return donePanel;
    }

    public JLabel getErrorMessageLabel() {
        return errorMessageLabel;
    }

   

    
}
